### ISSUE TITLE
Example label for x axis of SFS

### ISSUE THREAD

**Issue by sbreitbart** [shenglin-liu/vcf2sfs#8]
Hi there,

Can you suggest an example x axis label for the SFS plot? Thanks!

**Comment by shenglin-liu** [comment]
Hi,

"Allele count" should be fine. But I suggest checking some recent
literature.

Cheers,
Shenglin

**Comment by sbreitbart** [comment]
I'm not sure that makes sense for my data. And I wonder if I'm misinterpreting the plots or functions.

For example, I've filtered my data with Stacks' populations module so that the minimum minor allele frequency required to process a nucleotide site at a locus ranges from 0.1-1, yet after I use the gt2sfs.raw() function, I still end up with bars in the 1 and 2 positions on the sfs x axis from each of these vcfs. This suggests that my data retains alleles that are found only once or twice, which can't happen if the minimum minor allele frequency > 1/261 individuals, such as 0.5.

Are these x axis labels bins?

Also, as I have 261 individuals, I'd expect to see >10 labels on the x axis. Can I generate those additional bars?

Thanks!

**Comment by shenglin-liu** [comment]
The plotting functions were written in a way that all bins will be plotted no matter whether they are empty or not. Therefore, even if you filtered according to minimum MAF, all bins will be shown on the plot. The reason for this is that any 1-dimensional SFS should span from 0 to 2n (assuming diploid, n being sample size), although some bins might be empty depending on the filtering and folding. Software like dadi require all the bins, empty or not, to be existent in the input file. My plotting functions plot all the bins so that you can make sure that your SFS was properly created. Readers will also easily spot whether the SFS was filtered or folded by looking at the plot.

Each bar is a bin of allele count. x-axis label should be "allele count" or something equivalent. x-axis tick labels range from 0 to 2n, representing allele counts.

I'm not sure what you mean by 10 labels. Do you mean 10 bins? Number of bins should always be an odd number for diploids. Also, the number of bins generated by gt2sfs.raw() will depend on the popmap file and which population you are making the SFS for. Only if you assign all the individuals in the popmap file into one single population, you will see a SFS with 523 bins.

Hope this helps.

**Comment by sbreitbart** [comment]
Hi Shenglin,

Thank you so much for your fast and thorough replies. I'll try to be more specific about my question. I'm sure we'll figure it out!

My confusion stems from the fact that I see bars in x-axis bins I shouldn't. For example, here's my code:

```
# create genotype table with vcf with no missing data and a minimum minor allele frequency of 0.05:
mygt <- vcf2gt(my_vcf, pop_map_file)

# look at mygt structure
str(mygt)

# output:
# List of 2
# $ popmap  : chr [1:261] "67" "79" "40" "47" ...
# $ genotype: int [1:177, 1:261] 0 0 0 0 1 1 1 1 1 1 ...

# create SFS with  a population called "2"
sfs <- gt2sfs.raw(mygt, "2") 

# look at sfs structure. There are only 11 bins
str(sfs)

# output:
# 'table' num [1:11(1d)] 45 48 27 24 11 6 8 4 0 4 ...
# - attr(*, "dimnames")=List of 1
#  ..$ 2: chr [1:11] "0" "1" "2" "3" ...

# plot the SFS
plot.sfs(sfs)
```

Here is the plotted SFS.
![image](https://github.com/shenglin-liu/vcf2sfs/assets/16941522/3596aa68-7cb9-4f8a-a41b-95e0ca773fe1)

Again, I shouldn't be seeing alleles found only once (and thus in the "1" bin) because the minimum minor allele frequency is 0.05, and 5% of 261 individuals is ~13. So I'd expect the x axis to start around 13 for this dataset.

Does this make more sense? Are there things that I'm not understanding about the code? Thanks again for your help.

**Comment by shenglin-liu** [comment]
Hi,

Thanks for clarifying the question. Now I understand the problem.

What you are expecting (x axis starting around 13) will only happen if you include all 261 individuals in your SFS. But here you are creating a SFS for a population called "2" which contains 5 individuals. Because your MAF filtering was made for all 261 individuals, but not for population "2", it makes sense that you will see bars at bin 1, etc.

PS1: Judging from the result of str(mygt), your 261 individuals were grouped into may populations. I can see at least 5 populations, i.e., "67" "79" "40" "47" "2". If you want to create a SFS for all 261 individuals, you need to make sure they all belong to the same population.

PS2: If your species is diploid, you should not expect the SFS to start from ~13. It should start at 27.

Cheers,
Shenglin

**Comment by sbreitbart** [comment]
Thank you so much Shenglin! This makes sense now.
